[tool.poetry.dependencies]
python = "^3.10"
flask = "2.1.0"
pycaret = "3.2.0"
numpy = "1.23.1"
poetry = "1.7.1"
hydra-core = "1.3.2"
dvc = "3.42.0"
streamlit = "1.30.0"
gunicorn = "19.9.0"
Werkzeug = "2.1.2"